### ISSUE TITLE
Support for full language + locale culture strings?

### ISSUE THREAD

**Issue by willapp** [Dresel/RouteLocalization#38]
I have just picked up this package as we're looking to globalize our MVC application including route URLs. In the example all the localization is done against a simple language string such as "en" or "de", however we use a custom controller factory which sets the CurrentCulture and CurrentUICulture to a fully-localized culture such as "en-GB" or "fr-FR". This seems to break the localized URLs unless when I configure the localization I specify the full culture strings:

    const string DefaultCulture = "en-GB";
    ISet<string> acceptedCultures = new HashSet<string>() { defaultCulture, "fr-FR" };

However I would have thought that the localization should be able to just pick up the language ("en" or "fr") even when the thread has a full language and locale specified? Is it just doing an exact string match somewhere and if so can this behaviour be modified?

**Comment by Dresel** [comment]
How does your custom controller factory determine the current culture?

Do you plan to use `CultureSensitiveHttpModule` or `CultureSensitiveActionFilterAttribute` (which would overwrite / set current culture)?

Which functionality is broken? The only thing I could think of is `GetVirtualPath` from the LocalizationCollectionRoute (which indeed matches only excact strings)? Try to modifiy `GetLocalizedOrDefaultRoute` from `LocalizationCollectionRoute.cs` to

    protected RouteBase GetLocalizedOrDefaultRoute(string currentCulture)
    {
        LocalizationRoute route;

        LocalizedRoutesContainer.TryGetValue(currentCulture, out route);

        if (route == null)
        {
            // Try to get region independent culture
            CultureInfo cultureInfo = new CultureInfo(currentCulture);

            LocalizedRoutesContainer.TryGetValue(cultureInfo.TwoLetterISOLanguageName, out route);
        }

        return route ?? NeutralRoute;
    }

Does the example now works like you would expect?

**Comment by willapp** [comment]
It gets the culture from either a cookie (where the user has overridden their browser default), or the Request.UserLanguages - but this is mapped to a list of known/allowed cultures and a default set if the language isn't supported. In all cases, by the time the route logic is applied, the CurrentCulture and CurrentUICulture will always have a full language-locale set.

I tried applying your modified `GetLocalizedOrDefaultRoute` implementation and it does indeed solve my problem - are you able to apply this to your codebase and release an updated NuGet package version? I think this change makes your package more flexible as setting a language for the URL localization should work regardless of the locale.

FYI I have disabled both `CultureSensitiveHttpModule` and `CultureSensitiveActionFilterAttribute` as in our use-case the culture will always be set by the controller factory at a prior stage so there doesn't seem to be any need to use these.

**Comment by Dresel** [comment]
> It gets the culture from either a cookie (where the user has overridden their browser default), or the Request.UserLanguages - but this is mapped to a list of known/allowed cultures and a default set if the language isn't supported. In all cases, by the time the route logic is applied, the CurrentCulture and CurrentUICulture will always have a full language-locale set.

This is what `CultureSensitiveHttpModule ` can do (see Cookie / Browser behaviour [here](https://github.com/Dresel/RouteLocalization/issues/19#issuecomment-55503337)).

I'm just wondering: What if your logic sets "de-AT" for example because of the browser settings but the user requests an english (en) route (without having `CultureSensitiveActionFilterAttribute` enabled), the culture would still be "de-AT" - is this what you want?

**Comment by willapp** [comment]
The reason we aren't using the `CultureSensitiveHttpModule` is purely because the culture is set earlier in the pipeline during controller creation, and we don't want the URL localization to conflict with that as it could cause strange behaviour.

Yes for the time being we do want to keep the existing culture even if the user requests a route that isn't in the same culture - again it's tied to the above decision because some aspect of our content localization may have already happened before the route localization occurs so we don't want to switch culture mid-way through the pipeline and end up with mixed translated content on the page. However this is just our individual use-case and probably won't apply to many users.

Do you have plans to integrate the earlier change into the main package? It would be great for us if we can utilize this.

**Comment by Dresel** [comment]
Oh I see. I'm just asking because I think it would be a good idea to rework the action filter in combination with GetLocalizedOrDefaultRoute too, so that this use case could be handled:

* Accepted Cultures are set to "en", "en-US", "de", "de-AT"
* Routes are added for "en", "de"
* User requests a german route ("de"), Browser Languages are set to en-US, de-AT
* CultureSensitiveHttpModule sets culture to first accepted browser language "en-US"
* CultureSensitiveActionFilterAttribute detects the non regionalized route ("de") and should first try to set a regionalized culture (if in Browser Languages & Accepted Cultures) - "de-AT" for this example, if this is not possible stick to the non regionalized route culture ("de")

Nevertheless I will add the changes for GetLocalizedOrDefaultRoute together with some unit tests to back up and finally publish the new NuGet package over the weekend.

**Comment by Dresel** [comment]
I just published the changes with a new NuGet package, please test if it works.
