### ISSUE TITLE
Split the Web API parts to separate classes

### ISSUE THREAD

**Issue by brgrz** [Dresel/RouteLocalization#41]
Hey Dresel, would you mind if we split the Web API code parts to separate files instead of having conditional directives (#if, #endif)?

More than that, Web API localized routes make much less sense because in general you'd have one API which would be, in most cases, RESTful and English based and would server content for all cultures/locales using culture parameter which mostly won't be part of a route itself but provided as a querystring parameter. What do you think?

**Comment by Dresel** [comment]
Well the conditional directives make it easier to maintain (duplicate) code. It's the same way the asp.net code look like. What benefit would you have if I split the files? As far as I know this will not be necessary for the next version of asp.net because the namespaces for mvc / api are the same.

So you would like to have the possibility to use the route culture prefix as querystring parameter? It looks like you wont need RouteLocalization for this use case anyway?
