### ISSUE TITLE
Localised routes not used in ActionLinks

### ISSUE THREAD

**Issue by sharpie86** [Dresel/RouteLocalization#58]
I'm attempting to set up a variety of different cultures, with the following structure:
domain.com/ (neutral route),
domain.com/us (us),
domain.com/de (de).. and so on.

As the url's don't need translating for all English-based urls, I've simply created all of the original routes as neutral (`AddAsNeutralRoute` -> `TranslateInitialAttributes`) and then for each of the other English language cultures added a new set of prefixed routes (ala [Issue #18 ](https://github.com/Dresel/RouteLocalization/issues/18)).

Translated links for non-English languages are then added programmatically as per the documentation.

This successfully generates all of the desired urls, as can been seen via glimpse, and on the non-English cultures the correct (translated) urls are placed into the markup.  However, for the English-based cultures, only the neutral culture urls are ever used.  
Is there an issue with culture detection when different English-language cultures are used?

**Comment by Dresel** [comment]
So if I understood you correctly:

You added multiple (English) cultures with the same url.
When generating action links on a specific (English) culture, only neutral ones are generated?

Can you post your complete route config or add an repo?

I have tried it out for what I have understood but couldn't reproduce, see [issues/58](https://github.com/Dresel/RouteLocalization/tree/issues/58) branch or [RouteConfig.cs](https://github.com/Dresel/RouteLocalization/blob/cb282fb6587b877792a11a55ce12413400038ae1/Source/RouteLocalization.Mvc.Sample/App_Start/RouteConfig.cs) and [_Layout.cshtml](https://github.com/Dresel/RouteLocalization/blob/cb282fb6587b877792a11a55ce12413400038ae1/Source/RouteLocalization.Mvc.Sample/Views/Shared/_Layout.cshtml) directly.

**Comment by sharpie86** [comment]
Apologies for not being able to feed back incredibly specifically - I'm integrating this into a fairly large project that I can't really push into a repo, nor explicitly post all of the code used, so I'm trying to contrive a situation where I can reproduce the problem using your sample code.

I believe the problem lies in how I've set the thread culture. Because "en", "us", "de" aren't specific enough (or actually even proper cultures), I map these to "en-GB", "en-US" and "de-DE" respectively using a custom `IAuthorizationFilter` registered globally.

You can essentially replicate the behaviour I'm seeing by adding a contrived method to `CultureSensitiveActionFilterAttribute` as follows:
```
private CultureInfo GetCultureInfoForCultureName(string cultureName)
	    {
	        switch (cultureName)
	        {
                case "us": return new CultureInfo("en-US");
                case "de": return new CultureInfo("de-DE");
                default:return new CultureInfo("en-GB");
	        }
	    }
```
And then use this in the `OnActionExecuting` method where the culture is set (line 65).

This will appear as if everything is fine, but if you add the following lines to /Views/Home/Index.cshtml, you _should_ see that the urls they generate aren't correct for the /us/ path.
```
@Html.ActionLink("Home", "Index", "Home")
@Html.ActionLink("Book", "Book", "Home", new {@chapter = 4, @page=1}, null)
```
I was under the impression that the urls are generated using the culture route attribute as an identifier, but this behaviour leads me to believe that it's using the thread culture.  As such, is there a way of exposing this so that I can override it to effectively reverse the culture binding (thread culture en-GB -> route culture en)?

**Comment by Dresel** [comment]
Yes, you are right. The code for [GetVirtualPath](https://github.com/Dresel/RouteLocalization/blob/master/Source/RouteLocalization.Mvc/Routing/LocalizationCollectionRoute.cs#L73), which is responsible for link generation, is based on the assumption that thread culture and route culture are the same.

I see a few options:

- Use the same values for route and thread culture
- Always add culture as route value for link generation (this would override thread culture)
- Create a derived [LocalizationCollectionRoute](https://github.com/Dresel/RouteLocalization/blob/master/Source/RouteLocalization.Mvc/Routing/LocalizationCollectionRoute.cs), which overrides virtual path and uses route culture instead of thread culture, create a custom [IDirectRouteProvider](https://github.com/Dresel/RouteLocalization/blob/f9fc12a6694d81286ccdb1cdcf5e72861fd3a5e5/Source/RouteLocalization.Common/Routing/LocalizationDirectRouteProvider.cs) which creates instances of your derived LocalizationCollectionRoute and set this class for [Localization.LocalizationDirectRouteProvider](https://github.com/Dresel/RouteLocalization/blob/master/Source/RouteLocalization.Common/Localization.cs#L40)

I think I will change `GetVirtualPath` to consider route culture anyway, but I can't promise when the new package will be online (maybe next week).

Using thread culture has the advantage that if you are on a neutral page (maybe a page which is not translated yet) but the thread culture is set (e.g. loaded from cookie), the routes would still be rendered correctly.

**Comment by sharpie86** [comment]
Thanks for your help with this - I went with your third option in the end.  
It was relatively straightforward, though there was one extra step involved whereby I had to set the Configuration.LocalizationCollectionRoutes to the newly-created RouteProvider's RouteCollection, rather than allowing it to use it's default collection.
This now seems to be doing exactly what's required.
